import type { Metadata } from "next";
import { rethinkSans, inter } from "./fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${rethinkSans.variable} ${inter.variable} antialiased`}
      >
        <main className="min-h-screen flex items-center justify-center bg-gradient-radial">
          {children}
        </main>
      </body>
    </html>
  );
}
